### ISSUE TITLE
Force script to be exact last to load

### ISSUE THREAD

**Issue by JohnO413** [unFocus/Scripts-n-Styles#66]
This is a copy/paste from the plugin support page (I was slow to read your notes!)

I need to add a simple script to reverse the action of a plugin only on one or a few pages (it is active site wide). The plugin author recommends modifying the footer.php, but I would prefer not to do this. Using your plugin, I am able to inject this script intended to “hide” the plugin. But it does not load last, meaning NOT immediately before </body>. In fact, a few other theme scripts run (Avada theme) and then the plugin script runs. So it is literally the last thing loaded before the </body>. And the plugin remains active as it is the last script run.

The script is:
jQuery(document).ready(function($) {jQuery(“#sss-sidebar-source-div-1”).smartTabDrawer(“hide”);});

Is there a way force it to a lower priority or a way to force it to load last? The page is here: http://www.rosssolargroup.com/friends/ (NOTE: I have deliberately used bad code to cause the plugin to “break” on the page. Same result as effectively hiding it.)
Thanks! John

**Comment by WraithKenny** [comment]
You might look to see if there's a JavaScript event you could hook to, or attach your code to the "load" event instead of "ready". I'm interested in adding a priority option in SnS, but that's probably a long way off.
