### ISSUE TITLE
External Scripts for Single Page/Post

### ISSUE THREAD

**Issue by jamesdeluk** [unFocus/Scripts-n-Styles#69]
I hope I'm not missing something obvious; I have searched :)

One of my pages needs an external script. I don't want to include it in all pages because, well, it's not needed. So I don't want to manually enqueue it, or add it to all headers another way.

Is there a way to do this with SnS? SnS has the <script></script> tags already there, and I'd need to add the src inside the <>. So far I'm simply closing the tag, then opening another one (and not closing it myself) i.e. `<script>`</script><script src="">`</script>`. But I feel this isn't the best way...

What's the best solution?

Thanks!

**Comment by WraithKenny** [comment]
That is, indeed, the way to do it currently!

The plugin wasn't really built with that intent in mind, but it's not doing anything particularly tricky when outputting the script tags, so it has become the default work-around.

The next major version will include a way to do arbitrary html in the head.
