### ISSUE TITLE
Execute PHP code 

### ISSUE THREAD

**Issue by rspadim** [unFocus/Scripts-n-Styles#72]
Could be possible include <?php code ?> inside HTML HEAD / HTML BODY?
i need to integrate with wp membership plugin and avoid scripts n styles when member don't have signature permission

**Comment by rspadim** [comment]
something like https://stackoverflow.com/questions/1309800/php-eval-that-evaluates-html-php

eval(' ?>'.$htmlandphp.'<?php ');

**Comment by WraithKenny** [comment]
No, this plugin isn't intended for that sort of thing. For that, you'd be better off just editing the Theme files via the Appearance Editor, or writing a simple plugin.
