### ISSUE TITLE
Is a Manual Update available?

### ISSUE THREAD

**Issue by BrontideRob** [unFocus/Scripts-n-Styles#73]
Do you provide a method for doing a manual update?  I'm hitting a "Update Failed: Could not create directory." error that I know is due to security lock downs at my hosting site.  I have the same issue with WordPress updates.  They provide a manual update process that works well.
Fair winds

**Comment by WraithKenny** [comment]
FTP is the manual way. Just unzip the archive from the WordPress repo: https://downloads.wordpress.org/plugin/scripts-n-styles.3.5.1.zip
and upload it. (I don't know that there's any other manual way.)
